# Prueba de ejecución

In [1]:
library("duckdb")

Loading required package: DBI

In [2]:
# to start an in-memory database
con <- dbConnect(duckdb())

duckdb is storing downloaded extensions and secrets under ~/.duckdb:
ℹ /home/milo/.duckdb
This persists across sessions and is shared with the DuckDB CLI and other clients.
ℹ Run duckdb(shared_home = FALSE) to use a temporary directory instead.
ℹ See ?duckdb_storage for details and alternatives.

In [3]:
dbExecute(con, "
INSTALL iceberg;
LOAD iceberg;

CREATE SECRET iceberg_secret (
             TYPE iceberg,
             CLIENT_ID 'spark',
             CLIENT_SECRET '<CLIENT_SECRET>',
             OAUTH2_SERVER_URI '<OAUTH2_SERVER_URI>',
             OAUTH2_SCOPE 'lakekeeper'     
	);
	
LOAD httpfs;
ATTACH 'cepcan' AS cepcan (
   TYPE iceberg,
   SECRET iceberg_secret, -- pass a specific secret name to prevent ambiguity
   ENDPOINT '<ENDPOINT>'
);
")

[1] 0

In [4]:
# retrieve the items again
res <- dbGetQuery(con, "SELECT * FROM cepcan.pyiceberg_namespace.cdata;")
res

       Municipio
1      001 Abalá
2      001 Abalá
3      001 Abalá
4      001 Abalá
5      001 Abalá
6      001 Abalá
7      001 Abalá
8      001 Abalá
9      001 Abalá
10     001 Abalá
11     001 Abalá
12     001 Abalá
13     001 Abalá
14     001 Abalá
15     001 Abalá
16     001 Abalá
17     001 Abalá
18     001 Abalá
19     001 Abalá
20     001 Abalá
21     001 Abalá
22     001 Abalá
23     001 Abalá
24     001 Abalá
25     001 Abalá
26     001 Abalá
27     001 Abalá
28     001 Abalá
29     001 Abalá
30     001 Abalá
⋮      ⋮
685090 570 Zimatlán de Álvarez
685091 570 Zimatlán de Álvarez
685092 570 Zimatlán de Álvarez
685093 570 Zimatlán de Álvarez
685094 570 Zimatlán de Álvarez
685095 570 Zimatlán de Álvarez
685096 570 Zimatlán de Álvarez
685097 570 Zimatlán de Álvarez
685098 570 Zimatlán de Álvarez
685099 570 Zimatlán de Álvarez
685100 570 Zimatlán de Álvarez
685101 570 Zimatlán de Álvarez
685102 570 Zimatlán de Álvarez
685103 570 Zimatlán de Álvarez
685104 570 Zimatlán de Álvarez
685105 570 Zimatlán de Álvarez
685106 570 Zimatlán de Álvarez
685107 570 Zimatlán de Álvarez
685108 570 Zimatlán de Álvarez
685109 570 Zimatlán de Álvarez
685110 570 Zimatlán de Álvarez
685111 570 Zimatlán de Álvarez
685112 570 Zimatlán de Álvarez
685113 570 Zimatlán de Álvarez
685114 570 Zimatlán de Álvarez
685115 570 Zimatlán de Álvarez
685116 570 Zimatlán de Álvarez
685117 570 Zimatlán de Álvarez
685118 570 Zimatlán de Álvarez
685119 570 Zimatlán de Álvarez
       Actividad económica
1      Rama 1125 Acuicultura
2      Rama 1141 Pesca
3      Rama 1151 Servicios relacionados con la agricultura
4      Rama 1152 Servicios relacionados con la cría y explotación de animales
5      Rama 1153 Servicios relacionados con el aprovechamiento forestal
6      Rama 2111 Extracción de petróleo y gas
7      Rama 2121 Minería de carbón mineral
8      Rama 2122 Minería de minerales metálicos
9      Rama 2123 Minería de minerales no metálicos
10     Rama 2131 Servicios relacionados con la minería
11     Rama 2211 Generación, transmisión, distribución y comercialización de energía eléctrica
12     Rama 2212 Suministro de gas natural por ductos al consumidor final
13     Rama 2213 Captación, tratamiento y suministro de agua
14     Rama 2361 Edificación residencial
15     Rama 2362 Edificación no residencial
16     Rama 2371 Construcción de obras para el suministro de agua, petróleo, gas, energía eléctrica y telecomunicaciones
17     Rama 2372 División de terrenos y construcción de obras de urbanización
18     Rama 2373 Construcción de vías de comunicación
19     Rama 2379 Otras construcciones de ingeniería civil
20     Rama 2381 Cimentaciones, montaje de estructuras prefabricadas y trabajos en exteriores
21     Rama 2382 Instalaciones y equipamiento en construcciones
22     Rama 2383 Trabajos de acabados en edificaciones
23     Rama 2389 Otros trabajos especializados para la construcción
24     Rama 3111 Elaboración de alimentos balanceados para animales
25     Rama 3112 Molienda de granos y de semillas y obtención de aceites y grasas
26     Rama 3113 Elaboración de azúcares, chocolates, dulces y similares
27     Rama 3114 Conservación de frutas, verduras, guisos y otros alimentos preparados
28     Rama 3115 Elaboración de productos lácteos
29     Rama 3116 Matanza, empacado y procesamiento de carne de ganado, aves y otros animales comestibles
30     Rama 3117 Preparación y envasado de pescados y mariscos
⋮      ⋮
685090 Rama 6241 Servicios de orientación y trabajo social
685091 Rama 6242 Servicios comunitarios de alimentación, refugio y emergencia
685092 Rama 6243 Servicios de capacitación para el trabajo para personas desempleadas, subempleadas o con discapacidad
685093 Rama 6244 Guarderías
685094 Rama 7111 Compañías y grupos de espectáculos artísticos y culturales
685095 Rama 7112 Deportistas y equipos deportivos profesionales
685096 Rama 7113 Promotores de espectáculos artísticos, culturales, deportivos y similares
685097 Rama 7114 Agentes y representantes de artistas, deportistas y similares
685098 Rama 7115 Artistas, escritores y técnicos independientes
685099 Rama 7121 Museos, sitios históricos, zoológicos y similares
685100 Rama 7131 Parques con instalaciones recreativas y casas de juegos electrónicos
685101 Rama 7132 Casinos, loterías y otros juegos de azar
685102 Rama 7139 Otros servicios recreativos
685103 Rama 7211 Hoteles, moteles y similares
685104 Rama 7212 Campamentos y albergues recreativos
685105 Rama 7213 Pensiones y casas de huéspedes, y departamentos y casas amueblados con servicios de hotelería
685106 Rama 7223 Servicios de preparación de alimentos por encargo
685107 Rama 7224 Centros nocturnos, bares, cantinas y similares
685108 Rama 7225 Servicios de preparación de alimentos y bebidas alcohólicas y no alcohólicas
685109 Rama 8111 Reparación y mantenimiento de automóviles y camiones
685110 Rama 8112 Reparación y mantenimiento de equipo electrónico y de equipo de precisión
685111 Rama 8113 Reparación y mantenimiento de maquinaria y equipo agropecuario, industrial, comercial y de servicios
685112 Rama 8114 Reparación y mantenimiento de artículos para el hogar y personales
685113 Rama 8121 Salones y clínicas de belleza, baños públicos y bolerías
685114 Rama 8122 Lavanderías y tintorerías
685115 Rama 8123 Servicios funerarios y administración de cementerios
685116 Rama 8124 Estacionamientos y pensiones para vehículos automotores
685117 Rama 8129 Servicios de revelado e impresión de fotografías y otros servicios personales
685118 Rama 8131 Asociaciones y organizaciones comerciales, laborales, profesionales y recreativas
685119 Rama 8132 Asociaciones y organizaciones religiosas, políticas y civiles
       UE Unidades económicas Año Censal diversity ubiquity mcp eci
1      0                      2023       21         472     0   -0.6648572
2      0                      2023       21         304     0   -0.6648572
3      0                      2023       21         269     0   -0.6648572
4      0                      2023       21         117     0   -0.6648572
5      0                      2023       21          21     0   -0.6648572
6      0                      2023       21          17     0   -0.6648572
7      0                      2023       21           8     0   -0.6648572
8      0                      2023       21         103     0   -0.6648572
9      0                      2023       21         381     0   -0.6648572
10     0                      2023       21          53     0   -0.6648572
11     0                      2023       21          64     0   -0.6648572
12     0                      2023       21           9     0   -0.6648572
13     1                      2023       21        1906     1   -0.6648572
14     0                      2023       21         216     0   -0.6648572
15     0                      2023       21         222     0   -0.6648572
16     0                      2023       21         240     0   -0.6648572
17     0                      2023       21         237     0   -0.6648572
18     0                      2023       21         222     0   -0.6648572
19     0                      2023       21          93     0   -0.6648572
20     1                      2023       21         284     1   -0.6648572
21     0                      2023       21         222     0   -0.6648572
22     0                      2023       21         249     0   -0.6648572
23     0                      2023       21         163     0   -0.6648572
24     0                      2023       21         293     0   -0.6648572
25     0                      2023       21         342     0   -0.6648572
26     0                      2023       21         561     0   -0.6648572
27     0                      2023       21         567     0   -0.6648572
28     0                      2023       21        1127     0   -0.6648572
29     0                      2023       21         919     0   -0.6648572
30     0                      2023       21          51     0   -0.6648572
⋮      ⋮                      ⋮          ⋮         ⋮        ⋮   ⋮
685090  13                    2023       54         845     1   0.07123055
685091   0                    2023       54         253     0   0.07123055
685092   0                    2023       54          60     0   0.07123055
685093   2                    2023       54         405     1   0.07123055
685094   0                    2023       54         538     0   0.07123055
685095   0                    2023       54          71     0   0.07123055
685096   0                    2023       54         372     0   0.07123055
685097   0                    2023       54          43     0   0.07123055
685098   1                    2023       54         274     1   0.07123055
685099   0                    2023       54         234     0   0.07123055
685100   1                    2023       54         841     0   0.07123055
685101   0                    2023       54         231     0   0.07123055
685102   9                    2023       54         660     0   0.07123055
685103   7                    2023       54         890     0   0.07123055
685104   0                    2023       54          63     0   0.07123055
685105   0                    2023       54         586     0   0.07123055
685106   0                    2023       54         366     0   0.07123055
685107  12                    2023       54        1161     1   0.07123055
685108 234                    2023       54        1114     1   0.07123055
685109  63                    2023       54         738     0   0.07123055
685110   4                    2023       54         552     0   0.07123055
685111   6                    2023       54         565     0   0.07123055
685112  27                    2023       54         790     0   0.07123055
685113  54                    2023       54         481     0   0.07123055
685114  10                    2023       54         339     0   0.07123055
685115   5                    2023       54        1206     1   0.07123055
685116   5                    2023       54         336     0   0.07123055
685117   3                    2023       54         369     1   0.07123055
685118   0                    2023       54         968     0   0.07123055
685119   2                    2023       54        1231     0   0.07123055
       pci         density     coi        cog          rca       Entidad
1      -0.60170476 0.127474888 -0.7209931  0.328752607  0.000000 NA
2      -0.52837021 0.106811988 -0.7209931  0.523824749  0.000000 NA
3       0.92439446 0.074308453 -0.7209931  1.101944610  0.000000 NA
4       1.74990870 0.044232434 -0.7209931  1.647409030  0.000000 NA
5       3.39789276 0.026401363 -0.7209931  1.151537125  0.000000 NA
6       4.00458246 0.020216325 -0.7209931  1.638400397  0.000000 NA
7       2.68273908 0.023385461 -0.7209931  0.922778154  0.000000 NA
8       0.66982184 0.047952789 -0.7209931  1.280370497  0.000000 NA
9      -0.06693827 0.103133185 -0.7209931  0.568487238  0.000000 NA
10      3.91246954 0.024563722 -0.7209931  2.433513808  0.000000 NA
11      3.95252655 0.025976414 -0.7209931  2.791308448  0.000000 NA
12      7.94336832 0.009780831 -0.7209931  3.304188638  0.000000 NA
13     -2.17629270 0.270273488 -0.7209931  0.000000000  9.423874 31 Yucatán
14      2.99036430 0.044360942 -0.7209931  2.737274152  0.000000 NA
15      3.34955147 0.045282779 -0.7209931  3.082903142  0.000000 NA
16      3.06285853 0.048298646 -0.7209931  2.657071921  0.000000 NA
17      2.90588338 0.049008867 -0.7209931  2.521643605  0.000000 NA
18      2.88899399 0.047467637 -0.7209931  2.580957923  0.000000 NA
19      4.90710325 0.025884937 -0.7209931  3.580538731  0.000000 NA
20      2.62017426 0.069549383 -0.7209931  0.000000000 18.738392 31 Yucatán
21      3.40867646 0.043503963 -0.7209931  3.182940070  0.000000 NA
22      3.56445075 0.047437199 -0.7209931  3.053184235  0.000000 NA
23      4.43892538 0.033282436 -0.7209931  3.560346570  0.000000 NA
24      1.62477577 0.067806432 -0.7209931  1.530566012  0.000000 NA
25      1.51169571 0.073565613 -0.7209931  1.407343627  0.000000 NA
26     -0.65111785 0.142591894 -0.7209931  0.319916136  0.000000 NA
27     -0.33733101 0.134336041 -0.7209931  0.419020392  0.000000 NA
28     -1.02548946 0.196107298 -0.7209931  0.073292873  0.000000 NA
29     -1.16976997 0.189525146 -0.7209931 -0.008939556  0.000000 NA
30      3.99671804 0.025008617 -0.7209931  2.156820696  0.000000 NA
⋮      ⋮           ⋮           ⋮          ⋮            ⋮         ⋮
685090 -0.36829379 0.39084945  0.3898507  0.0000000    2.2234896 20 Oaxaca
685091  2.27290673 0.18288411  0.3898507  2.1521569    0.0000000 NA
685092  5.44950013 0.07529316  0.3898507  3.5419280    0.0000000 NA
685093  1.93622521 0.25134562  0.3898507  0.0000000    1.2498803 20 Oaxaca
685094 -0.32984484 0.34365414  0.3898507  0.4568787    0.0000000 NA
685095  4.34785986 0.08370504  0.3898507  2.9800537    0.0000000 NA
685096  1.71226999 0.24267785  0.3898507  1.7141088    0.0000000 NA
685097  5.72624533 0.06395845  0.3898507  3.3816426    0.0000000 NA
685098  2.04555443 0.22681601  0.3898507  0.0000000    3.3021530 20 Oaxaca
685099  1.59793552 0.19207003  0.3898507  1.7091174    0.0000000 NA
685100 -0.40936241 0.39547774  0.3898507  0.3626740    0.3059473 20 Oaxaca
685101  2.08649740 0.16702058  0.3898507  2.1141688    0.0000000 NA
685102  0.86308058 0.30514981  0.3898507  1.2446953    0.8456698 20 Oaxaca
685103 -0.72064227 0.39672478  0.3898507  0.3473817    0.9483306 20 Oaxaca
685104  2.95989093 0.10636604  0.3898507  1.7813968    0.0000000 NA
685105 -0.40808835 0.35196674  0.3898507  0.4517394    0.0000000 NA
685106  1.94427785 0.22172334  0.3898507  1.9906298    0.0000000 NA
685107 -0.81331262 0.44075639  0.3898507  0.0000000    1.2851622 20 Oaxaca
685108 -0.64070897 0.41036346  0.3898507  0.0000000    1.0902900 20 Oaxaca
685109  0.38980596 0.32480899  0.3898507  0.9397698    0.8008723 20 Oaxaca
685110  0.63075821 0.29861490  0.3898507  1.1495833    0.4068954 20 Oaxaca
685111  0.79737145 0.29012396  0.3898507  1.2067661    0.9687689 20 Oaxaca
685112 -0.09571403 0.35908927  0.3898507  0.6666312    0.8309765 20 Oaxaca
685113  1.51260933 0.25402795  0.3898507  1.6497123    0.5987157 20 Oaxaca
685114  1.77517292 0.21963002  0.3898507  1.7893822    0.8263672 20 Oaxaca
685115 -0.64597015 0.44780019  0.3898507  0.0000000    1.8568163 20 Oaxaca
685116  1.77283748 0.24217084  0.3898507  1.6858711    0.8825596 20 Oaxaca
685117  1.56951583 0.25609821  0.3898507  0.0000000    1.2610108 20 Oaxaca
685118 -0.50914726 0.38792936  0.3898507  0.5383838    0.0000000 NA
685119 -1.61034556 0.42436413  0.3898507  0.2706056    0.4878323 20 Oaxaca
       A111A Producción bruta total (millones de pesos)
1      NA
2      NA
3      NA
4      NA
5      NA
6      NA
7      NA
8      NA
9      NA
10     NA
11     NA
12     NA
13     NA
14     NA
15     NA
16     NA
17     NA
18     NA
19     NA
20     NA
21     NA
22     NA
23     NA
24     NA
25     NA
26     NA
27     NA
28     NA
29     NA
30     NA
⋮      ⋮
685090      NA
685091      NA
685092      NA
685093      NA
685094      NA
685095      NA
685096      NA
685097      NA
685098      NA
685099      NA
685100      NA
685101      NA
685102      NA
685103   4.491
685104      NA
685105      NA
685106      NA
685107   3.727
685108 110.075
685109  18.254
685110   0.894
685111   3.149
685112   6.827
685113   9.359
685114   1.260
685115   5.815
685116   0.190
685117      NA
685118      NA
685119      NA

In [ ]:
# Writing to Iceberg
dbExecute(con, "
CREATE SCHEMA cepcan.sales;
USE cepcan.sales;

CREATE TABLE cepcan.sales.events (
    id INTEGER,
    event_name VARCHAR,
    event_time TIMESTAMP
);
")

In [6]:
# Table Properties
## Existing properties can be inspected and modified with the property functions:
dbExecute(con, "
 -- View properties
SELECT * FROM iceberg_table_properties(cepcan.sales.events);   
")

[1] 0

In [7]:
# Inserting Data
dbExecute(con, "
INSERT INTO cepcan.sales.events
VALUES (1, 'click', TIMESTAMP '2026-06-01 10:00:00');
")

[1] 1

In [8]:
#
dbGetQuery(con, "SELECT * FROM cepcan.sales.events;")

  id event_name event_time
1 1  click      2026-06-01 10:00:00
2 1  click      2026-06-01 10:00:00